
spring:
  kafka:
    bootstrap-servers: http://kafka-service:9092
    consumer:
      group-id: waya
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

xero:
  upload:
    transactions: https://api.xero.com/api.xro/2.0/BankTransactions
  fetch:
    transactions: https://api.xero.com/api.xro/2.0/BankTransactions
  token-url: https://identity.xero.com/connect/token
  client-id: test-clientId
  client-secret: test-clientSecret
  grant-type: client_credentials
  scope: offline_access

