
spring:
  kafka:
    bootstrap-servers: http://kafka-service:9092
    consumer:
      group-id: waya
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

xero:
  upload:
    transactions: https://api.xero.com/api.xro/2.0/BankTransactions
  fetch:
    transactions: https://api.xero.com/api.xro/2.0/BankTransactions
  token-url: https://identity.xero.com/connect/token
  client-id: test-clientId
  client-secret: test-clientSecret
  grant-type: client_credentials
  scope: offline_access

waya:
  transaction: https://services.staging.wayabank.ng/temporal-service/api/v1/wallet/account/transactions/
  token: serial eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbeyJjcmVhdGVkQXQiOiIwNy0xMS0yMDIyIDEwOjM4OjI3IiwidXBkYXRlZEF0IjoiMDctMTEtMjAyMiAxMDozODoyNyIsImNyZWF0ZWRCeSI6Ik1HUiIsIm1vZGlmaWVkQnkiOiJNR1IiLCJpZCI6MTAsIm5hbWUiOiJST0xFX1VTRVJfT1dORVIiLCJkZXNjcmlwdGlvbiI6IkNVU1RPTUVSIiwiZGVmYXVsdCI6dHJ1ZSwiYWRtaW5Sb2xlIjpmYWxzZX0seyJjcmVhdGVkQXQiOiIwNy0xMS0yMDIyIDEwOjM4OjI3IiwidXBkYXRlZEF0IjoiMDctMTEtMjAyMiAxMDozODoyNyIsImNyZWF0ZWRCeSI6Ik1HUiIsIm1vZGlmaWVkQnkiOiJNR1IiLCJpZCI6MjIsIm5hbWUiOiJST0xFX0FETUlOX0FQUCIsImRlc2NyaXB0aW9uIjoiU1lTVEVNIEFDQ09VTlQiLCJkZWZhdWx0IjpmYWxzZSwiYWRtaW5Sb2xlIjp0cnVlfV0sImlkIjoyMTUzLCJzdWIiOiJlZGNlZWJlZUBnbWFpbC5jb20iLCJpYXQiOjE2ODE0MTQwMjgsImV4cCI6MTcxMjk3MTYyOH0.jkJn_wCS9G5yDw2yOBkhC4ogW0kPkl2AyZ6CdYX8KOdiqRLRxkV-CBVqMkLXne2kZ9SmXVNke0h6RbbNdxklPQ

